LLVM apt repo is back up. Using Clang16

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -24,13 +24,19 @@ jobs:
           submodules: recursive
       - name: Install clang-${{ env.clang-version }}
         run: |
-          sudo apt-get update
-          sudo apt-get install -y clang-format-${{ env.clang-version }} clang-tidy-${{ env.clang-version }}
+          sudo apt-get --quiet update
+          wget https://apt.llvm.org/llvm.sh -O ${{ runner.temp }}/llvm_install.sh
+          chmod +x ${{ runner.temp }}/llvm_install.sh
+          if sudo ${{ runner.temp }}/llvm_install.sh ${{ env.clang-version }}; then
+            sudo apt-get install -y clang-format-${{ env.clang-version }} clang-tidy-${{ env.clang-version }} || exit 1
+          else
+            echo "Installation from script failed."
+            exit 1
+          fi
           echo "CC=clang-${{ env.clang-version }}" >> $GITHUB_ENV
           echo "CXX=clang++-${{ env.clang-version }}" >> $GITHUB_ENV
       - name: Install OpenCV
         run: |
-          sudo apt-get --quiet update
           sudo apt-get install --no-install-recommends libopencv-dev
       - name: Generate compilation database
         run: |
